### PR TITLE
Changing createOrUpdatePassword rules error data structure

### PR DESCRIPTION
**Pull request by Oluane**
This PR changes the data structure of the rules error thrown by `createOrUpdatePassword`. 

It is now a one-level object containing strings. 

A new util function which flattens nested object recursively was added.

### CODE REVIEW

**Comment by Fenntasy** [comment]
Task linked: [CU-f51rh8 [management] - Changing error data structure in CreateOrUpdatePassword mutation](https://app.clickup.com/t/f51rh8)

**Comment by Fuzznimp** [comment]
Is `PasswordRules` used somewhere or can we remove it?

**Comment by Oluane** [comment]
> Is `PasswordRules` used somewhere or can we remove it?

Yes, it is still used inside `createOrUpdatePassword` function.

**Review by Fuzznimp — APPROVED** [review]
Good job!!

**Pull request merged**
